apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  clusterIP: None
  ports:
  - port: 35000
  selector:
    app: telegraf
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf-acc
      containers:
      - image: image-telegraf
        name: container-telegraf
        imagePullPolicy: Never
        env:
          # Use secret in real usage
        - name: TELEGRAF_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 35000
          name: telegraf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-acc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf-acc
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-acc
  labels:
    app: telegraf